import { cookies } from "next/headers";
import CsFooter from "@/components/Footer/Footer";
import CsNavbar from "@/components/Navbar/Navbar";
import "@/scss/site.scss";
import {
  DEVICE_THEME_COOKIE,
  PREFERRED_THEME_COOKIE,
  Themes,
} from "@/ts/Themes";
import CsOnPageLoad from "@/components/OnPageLoad/OnPageLoad";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  let theme = cookieStore.get(PREFERRED_THEME_COOKIE)?.value || Themes.Auto;
  let deviceTheme = cookieStore.get(DEVICE_THEME_COOKIE)?.value || undefined;
  if (theme === Themes.Auto) {
    theme = deviceTheme || Themes.Light;
  }

  return (
    <html lang="en" data-bs-theme={theme}>
      <body>
        <CsNavbar />
        {children}
        <CsFooter />
        <CsOnPageLoad />
      </body>
    </html>
  );
}
