import { cookies } from "next/headers";
import CsFooter from "@/components/Footer/Footer";
import CsNavbar from "@/components/Navbar/Navbar";
import CsOnPageLoad from "@/components/OnPageLoad/OnPageLoad";
import "@/scss/site.scss";
import {
  DEVICE_THEME_COOKIE,
  PREFERRED_THEME_COOKIE,
  Themes,
} from "@/ts/Themes";

export const metadata = {
  title: "Example Next JS App",
  description: "Generated by create next app",
  authors: [{ name: "Max Robinson", url: "https://maxrobinson.net" }],
  openGraph: {
    type: "website",
    images: "/img/doge.png",
  },
  twitter: {
    images: "/img/doge.png",
    card: "summary",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();

  let theme = cookieStore.get(PREFERRED_THEME_COOKIE)?.value || Themes.Auto;
  let deviceTheme = cookieStore.get(DEVICE_THEME_COOKIE)?.value || undefined;
  if (theme === Themes.Auto) {
    theme = deviceTheme || Themes.Light;
  }

  return (
    <html lang="en" data-bs-theme={theme}>
      <body>
        <CsNavbar />
        {children}
        <CsFooter />
        <CsOnPageLoad />
      </body>
    </html>
  );
}
